name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install

      - name: Run frontend (serve)
        working-directory: ./frontend
        run: |
          npm start &

      - name: Wait for the server to start
        run: |
          sleep 5

      - name: Check if the server is running
        run: |
          curl http://localhost:3000
